before_install:
- sudo apt-get install curl jq sed git
- gem install fpm
script:
- "./update_packages"
env:
  global:
    secure: Pu7COxtpkichu/ob3+/otpQ9/6viyZ+NX7CDiYzoTnjMT0CkVU7EtJe6dyUrRB+l+xWCP7rCm8wADvqiVZ616fykYvR0odnyblS0vqwMBakxrm5Qhz4NmHo9oLfroPtFBmiGqivrzNEMj4xuqq3MfqLF5ySQc1j4e961wxDh4pypKwBClDJJhEj9tj+vMqvxYxwJjSXPIF1MoGswLfnfnxAKaWpoxtlCGxfrrDJgZxWqcHbAisQYM1+uSuplrYaDQXVKaSuVccpOZCdbYC4uH/R76EMhafZdf2UrP0qwjf5mTAU4uQKFES0ufO/nmpVA22Qw7Hjdw/I9hDHSUijRLCzG2miQzd1rSduf7XurRlmyxWrN/b+ZBwsiyfOBwGap/3bwc2NpXihoa76ANSLb1bFW3Mz1A22WchreQOyxeLWrzqpeOt1Plz5t9EUTrifFeJZF8hLr0+bo3mIWbqqfRoRMpNqL4OvKvEAdpL+e0f0nAzQRNL2rSMKizg33aCzmQo41KgswTPUrLm2kkf7Eu4ncfMhpuDkTMn8ouJM1mJ1n5KMZ9z2ZobCCAliZ1RLSxG4IWYREpB0L1DI+WNTHsLb5gg1Gq3NmRZfVtcM3T164uUX2AlW3F93eF8JjfFhEDxlhIqYFJ0sb11+js7+kSVLg8cd6virDxs2U/aPMlhA=
