name: Build & Publish
on:
  schedule:
    - cron: "0 4/6 * * *"

jobs:
    build:
        runs-on: ubuntu-22.04
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENCRYPTED_E60E2D0D0CA0_KEY: ${{ secrets.ENCRYPTED_E60E2D0D0CA0_KEY }}
          ENCRYPTED_E60E2D0D0CA0_IV: ${{ secrets.ENCRYPTED_E60E2D0D0CA0_IV }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install dependencies
              run: sudo ./docker/install-dependencies

            - name: Do key handling
              run: ./docker/decrypt

            - name: Update packages
              run: ./update-packages

            - name: Publish packages
              run: ./publish-to-s3

            - name: Create commit variable
              run: |
                echo 'GIT_COMMIT_MSG<<EOF' >> $GITHUB_ENV
                echo -e 'Package updates!\n' >> $GITHUB_ENV
                [ -f commit.txt ] && cat commit.txt >> $GITHUB_ENV
                echo 'EOF' >> $GITHUB_ENV

            - name: Update repo
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: "${{ env.GIT_COMMIT_MSG }}"
                branch: master
                file_pattern: deb packages
